INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Dwa fotele w stylu Ludwika XVI', 'meble', 1930,12500.00,'2025-10-22','Fotele  z lat 30 –tych XX o klasycyzujacych formach  w typie Ludwika XVI. Drewniane obramienia foteli zdobione bogatą snycerką. Siedziska na sprężynach, tapicerowane tak jak oparcia i fragmenty podłokietników. Proste kanelowane nogi zakończone u góry rozetą wpisaną w kwadrat nawiązują do stylu  à la grecque. Fotele w dobrym stanie zachowania, drewno pokryte patyną, materiał w kilku miejscach wytarty, wymaga wymiany.' );
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Wiktoriański stolik','meble',1850,5900.00, '2025-05-17','Mebel z drewna mahoniowego, datowany na połowy XIX wieku. Oskrzynia ze ślepą szufladą i schowkiem otwieranym od góry z wnętrzem wyściełanym ciemno bordowym aksamitem. Podstawa złożona z toczonego trzpienia podtrzymującego pałąk w kształcie litery "U". Całość ustawiona na czteroramiennej platformie ze stopami w kształcie łap.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Secesyjna garderoba z początku XX wieku','meble',1900,7500.00,'2025-03-25','Garderoba z drewna mahoniowego, datowana na ok.1900/1910 rok. Mebel w formie ażurowej ścianki z wysuniętą podstawą na parasole i schowkiem na szczotki oraz pasty do butów. Cześć górna z lustrem w kształcie podkowy i dwoma rzędami mosiężnych wieszaków umieszczonych po dwóch  stronach ramy. Całość zwieńczona prostym gzymsem. Garderoba po renowacji, wykończona politurą i woskiem.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('XX-wieczne lustro w ciemnej ramie', 'akcesoria', 1987,3000.00,'2025-02-10','Lustro w sosnowej ramie, datowane na koniec XX wieku. Drewno bez renowacji, tafla ze śladami upływu czasu.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Neorokokowy komplet salonowy', 'meble',1950,12500.00,'2025-04-30','Komplet złożony z trzyosobowej sofy, stolika, dwóch krzeseł i taboretu. Meble z lat 50/60 –tych stylizowane na rokoko. Komplet tapicerowany, części drewniane zdobione snycerką Sofa o niskim, falistym oparciu i zaokrąglonych bokach.
Wymiary: Sofa: wys. 90 cm, szer.190 cm, gł. 70, wys. siedziska 43 cm. Krzesła: wys. 86 cm, szer. 50 cm, gł. 46 cm, wys. siedziska 43 cm. Stół: wys. 63 cm, śr. 91 cm Taboret: szer. 49 cm, gł. 40 , wys. siedziska 45 cm Całość w dobrym stanie, stolarka nie wymaga renowacji. Tkanina w niektórych miejscach posiada niewielkie wytarcia.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Talerz kryształowy na ciasto Huta Julia','akcesoria',2000,290.00,'2025-01-16','Talerz kryształowy na ciasto Huta Julia');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Ceramiczny talerzyk deserowy','akcesoria',2004,65.00,'2025-01-10','Ceramiczny talerzyk śniadaniowo-deserowy o średnicy 19,5 cm');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('6 szklanek do whisky 0,33 l + karafka','akcesoria',2017,370.00,'2025-02-12','RCR Cristalleria Italiana, Włoska firma z zagłębia kryształowego w Toskanii która powstała w 1967 roku. Słynie z produkcji kryształów. Jej klasyczne rękodzieło połączone z nowoczesną technologią od ponad 40 lat zachwyca najwyższą jakością i nienagannym wyglądem.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Obraz olejny na półtnie H. Veeninga','obrazy',1912,4200.00,'2025-04-25','Holenderski obraz olejny na półtnie sygnowany H. Veeninga. Stan zachowania bardzo dobry, zdobiona rama.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Obraz olejny wiejski pejzaż zimą','obrazy',1910,3500.00,'2025-04-25','Obraz olejny, datowany na początek XX wieku, przedstawiający wiejski pejzaż zimą. Stan zachowania bardzo dobry, rama drewniana.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Obraz z pejzażem górskim','obrazy',1970,2100.00,'2025-04-25','Olej na płótnie z przestawieniem górskiego pejzażu. Obraz z lat 70/80 –tych XX wieku, oprawiony w stylową ramę.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Inkrustowany zegar kominkowy, XIX wiek','akcesoria',1870,3900.00,'2025-03-30','Niezwykle dekoracyjny, bogato inkrustowany zegar kominkowy. Zegar o architektonicznej formie nawiazującej do portyku ze spiralnymi  podwójnymi kolumnami o mosiężnych bazach i kapitelach. Inkrustacja  z motywem roślinnym  w trzech odcieniach metalu. Zegar wybija połówki i pełne godziny. ');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Zegar kominkowy ze szklanym kloszem','akcesoria',1925,2300.00,'2025-05-05',' Zegar  z ok. 1930 roku na drewnianej podstawie z nakładanym szklanym kloszem. Efektowna, metalowa obudowa zegara z emblematami mysliwskimi, zwieńczona pełnoplastyczną figurą mysliwego na koniu. Zegar nakrecany na kluczyk, wybija połówki i pełne godziny. Mechanizm sprawny, po gruntownej naprawie i przeglądzie zegarmistrzowskim. Klosz pekniety z tyłu na całej wysokości. Obudowa zegara z naprwaianą nogą.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Przedwojenny model jachtu','inne',1927,3500.00,'2025-02-20','Wiernie odwzorowany model jachtu, datowany na okres XX-lecia miedzywojennego. Stan zachowania bardzo dobry.');
INSERT INTO item (name, category, yearOfProduction, price, auctionEndDate, description) VALUES ('Duży gobelin', 'inne', 1920,1200.00,'2025-04-12','Z przedstawieniem sceny rodzajowej z grającymi w kule mężczyznami. Tkanina bez ramy naciągnięta na nowe krosna. Wielkość 120 x 90 cm. Stan zachowania bardzo dobry, tkanina nie ma uszkodzeń.');
